apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: app-build-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: github-listener
    interceptors:
    - ref:
        name: "github"
        kind: ClusterInterceptor
        apiVersion: triggers.tekton.dev
      params:
      - name: "addChangedFiles"
        value:
          enabled: true
    - ref:
        name: cel
      params:
      - name: "filter"
        value: 'body["ref"].contains("main") && body["repository"]["name"] == "simple-apps" && extensions.changed_files.matches("source")'
      - name: "overlays"
        value:
        - key: branch
          expression: "body.ref.split('/')[2]"
    bindings:
      - ref: app-build-binding
    template:
      ref: app-build-template
