apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: app-build-listener
  name: app-build-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-app-build-listener-interceptor
