apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: app-build-pr-
spec:
  pipelineRef:
    name: app-build
  params:
    - name: git-url
      value: https://github.com/marrober/secure-pipeline.git
    - name: git-revision
      value: main
    - name: app-dir
      value: source
    - name: dockerfile
      value: docker/Dockerfile
    - name: imagestream-url
      value: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/pacman
    - name: acs_central_endpoint
      value: acs-secret
    - name: acs_api_token
      value: acs-secret
    - name: roxctl-output-format 
      value: table
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  - name: resources
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  - name: secrets
    secret:
      secretName: gpg-public-key