apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: app-build-pr-
spec:
  pipelineRef:
    name: app-build
  params:
      # Use this Git URL to pull a simple sample application and dockerfile for the construction of the container image. 
      # Update this reference if you clone the repo and make changes or use a completely difference repo.
    - name: git-url
      value: https://github.com/marrober/secure-pipeline.git
      # Main branch of the git repo
    - name: git-revision
      value: main
      # Directory within the git repo that holds the dockerfile. The example dockerfile makes reference to 
      # files within this directory too.
    - name: app-dir
      value: source
      # Dockerfile for the creation of the new container image.
    - name: dockerfile
      value: ci/application-pipeline/04-dockerfile/dockerfile
      # The imagestream url for where the created container image will be stored. Update the namespace element if this is
      # created in a different namespace. also update the namespace file in the location namespace/namespace.yaml.
    - name: imagestream-url
      value: image-registry.openshift-image-registry.svc:5000/simple-pipeline-1/my-app
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  - name: resources
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
        
          requests:
            storage: 5Gi