apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-pipeline/build-base-image-pipeline.yaml
- 03-tasks/build-base-image.yaml
- 03-tasks/push-base-image.yaml
- 05-triggers/
- 06-cronjobs/base-image-check-and-rebuild.yaml
