apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-pipelines/pipeline.yaml
- 03-tasks/build.yaml
- 03-tasks/pushImageToOCPImageStream.yaml
- 05-triggers/
- 06-smee/deployment.yaml

