apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-pipelines/pipeline.yaml
- 03-tasks/build.yaml
- 03-tasks/pushImageToOCPImageStream.yaml
- 03-tasks/acs-image-build-check.yaml
- 03-tasks/verify-source-commits.yaml
- 03-tasks/update-and-commit-kustomization-file.yaml
- 03-tasks/pushImageToQuay.yaml
- 03-tasks/dir.yaml
- 03-tasks/new-build.yaml
- 04-triggers/
- 05-smee/deployment.yaml
- 01-pipelines/pipeline-direct-to-quay.yaml
