apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.apps.cluster-l6cp9.l6cp9.sandbox1607.opentlc.com/development/repository-1
  newTag: tk7bs
