apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/development/repository-1
  newTag: dg6m4
- name: quay.io/marrober/pacman
  newTag: 9gggd
