apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-build
spec:
  params:
    # Buildah step configuration parameters - storage driver and TLS settings.
    #
  - name: STORAGE_DRIVER
    type: string
    default: vfs
  - name: TLSVERIFY
    type: string
    default: 'false'
  - name: dockerfile
    type: string
    #
    # Git repository parameters
    #
  - name: git-url
    type: string
  - name: git-revision
    type: string
  - name: app-dir
    type: string
    #
    # OpenShift imagestream URL parameters
    #
  - name: imagestream-url
    type: string
    #
    # ACS Image check parameters
    #
  - name: acs_central_endpoint
    type: string
  - name: acs_api_token
    type: string
  - name: roxctl-output-format # Advanced Cluster Security image scan output format
    type: string
    #
    # Update the kustomize file for the new image
    #
  - name: repo_type
    type: string
  - name: myapp-cd-git-url
    type: string
  - name: my-app-cd-git-repo-name
    type: string
  - name: my-app-cd-git-repo-path-to-content-development
    type: string
  - name: my-app-cd-git-user-name
    type: string
  - name: my-app-cd-git-user-email
    type: string
  - name: my-app-cd-git-commit-comment-dev
    type: string
    #
    # Push image to quay.io
    #
  - name: quay-io-account
  - name: quay-io-repository
  tasks:
##------------------------------------------------------------------
# Git clone resources task
##------------------------------------------------------------------
    - name: git-clone-resources
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
      - name: verbose
        value: 'false'
      - name: deleteExisting
        value: 'true'
      taskRef:
        kind: ClusterTask
        name:  git-clone
      workspaces:
      - name: output
        workspace: resources
##------------------------------------------------------------------
# Verify source commits
##------------------------------------------------------------------
    - name: verify-source-commits
      runAfter:
      - git-clone-resources
      taskRef:
        kind: Task
        name: verify-source-commits
      workspaces:
      - name: repository
        workspace: resources
      - name: secrets
        workspace: secrets
##------------------------------------------------------------------
# Workspace definitions
##------------------------------------------------------------------
  workspaces:
    - name: resources
    - name: files
    - name: secrets
