apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-build-direct-to-quay
spec:
  params:
    # Buildah step configuration parameters - storage driver and TLS settings.
    #
  - name: STORAGE_DRIVER
    type: string
    default: vfs
  - name: TLSVERIFY
    type: string
    default: 'false'
  - name: dockerfile
    type: string
    #
    # Git repository parameters
    #
  - name: git-url
    type: string
  - name: git-revision
    type: string
  - name: app-dir
    type: string
  tasks:
##------------------------------------------------------------------
# Git clone resources task
##------------------------------------------------------------------
    - name: git-clone-resources
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.git-revision)
      - name: verbose
        value: 'false'
      - name: deleteExisting
        value: 'true'
      taskRef:
        kind: ClusterTask
        name:  git-clone
      workspaces:
      - name: output
        workspace: source
##------------------------------------------------------------------
# Listing
##------------------------------------------------------------------
    - name: listing
      params:
      - name: CONTEXT
        value: $(params.app-dir)
      - name: dockerfile
        value: $(params.dockerfile)
      runAfter:
      - git-clone-resources
      taskRef:
        kind: Task
        name: listing
      workspaces:
      - name: source
        workspace: source
      - name: files
        workspace: files
##------------------------------------------------------------------
# Build the container
##------------------------------------------------------------------
    - name: build
      params:
      - name: TLSVERIFY
        value: "$(params.TLSVERIFY)"
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
      - name: CONTEXT
        value: $(params.app-dir)
      - name: dockerfile
        value: $(params.dockerfile)
      - name: IMAGE
        value: 'quay.apps.cluster-l6cp9.l6cp9.sandbox1607.opentlc.com/development/repository-2:1'
      taskRef:
        kind: ClusterTask
        name: buildah
      runAfter:
      - listing
      workspaces:
      - name: source
        workspace: source
      - name: dockerconfig
        workspace: quay-auth-secret

##------------------------------------------------------------------
# Workspace definitions
##------------------------------------------------------------------
  workspaces:
    - name: source
    - name: files
    - name: gpg-public-key
#    - name: gpg-secret-key
    - name: quay-auth-secret
