apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: TLSVERIFY
      default: "false"
      description: Verify the TLS on the registry endpoint
      type: string
    - name: STORAGE_DRIVER
      description: The Buildah storage STORAGE_DRIVER
      type: string
    - name: app-dir
      type: string
    - name: dockerfile
      type: string
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  steps:
    - name: build
      command:
      - buildah
      - bud
      - --tls-verify=$(params.TLSVERIFY)
      - --storage-driver=$(params.STORAGE_DRIVER)
      - --root
      - /files/buildah-containers
      - --layers
      - -f
      - $(params.dockerfile)
      - -t
      - my-container-image
      - .
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
      resources: {}
      securityContext:
        capabilities:
          add:
          - SETFCAP
      workingDir: /resources/$(params.app-dir)
    - name: list-images
      command:
      - buildah
      - images
      - --storage-driver=$(params.STORAGE_DRIVER)
      - --root
      - /files/buildah-containers
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
      resources: {}
      securityContext:
        capabilities:
          add:
          - SETFCAP
      workingDir: /
  volumes:
    - emptyDir: {}
      name: envparams
  workspaces:
    - mountPath: /files
      name: files
    - mountPath: /resources
      name: resources

