apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: listing
spec:
  params:
      type: string
    - name: app-dir
      type: string
    - name: dockerfile
      type: string
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  steps:
    - name: list-1
      command:
      - ls -al /files
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
    - name: list-2
      command:
      - ls -al /source
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
    - name: list-3
      command:
      - ls -al .
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
    - name: pwd
      command:
      - pwd
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
      workingDir: $(workspaces.source.path)
  workspaces:
    - mountPath: /files
      name: files
    - mountPath: /source
      name: source

