apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: listing
spec:
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  steps:
    - name: pwd
      command:
      - pwd
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
      workingDir: $(workspaces.source.path)
    - name: list-1
      command:
      - ls 
      - -al 
      - .
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
    - name: list-2
      command:
      - ls 
      - -al 
      - /source
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
  workspaces:
    - mountPath: /files
      name: files
    - mountPath: /source
      name: source

