apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image-to-ocp
spec:
  params:
    - name: imagestream-url
      type: string
    - name: STORAGE_DRIVER
      type: string
    - name: TLSVERIFY
      type: string
    - name: pipelineRunName
      type: string
  results:
    - name: new-tag
      type: string
    - name: IMAGE_DIGEST
      type: string
    - name: IMAGE_URL
      type: string
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  steps:
    - name: push-to-imagestream
      script: >-
        #!/usr/bin/env bash

        set +x

        var1=$(params.pipelineRunName)

        echo $var1

        var2=${var1:(${#var1} - 5):${#var1}}

        tag=$var2

        echo $tag

        echo -n $tag >  $(results.new-tag.path)

        buildah push --storage-driver=$(params.STORAGE_DRIVER) \

        --tls-verify=$(params.TLSVERIFY) --root /files/buildah-containers \

        --digestfile /tmp/image-digest \

        localhost/my-container-image:latest \

        docker://$(params.imagestream-url):$tag

        cat /tmp/image-digest | tee $(results.IMAGE_DIGEST.path)

        echo "localhost/my-container-image:latest" | tee $(results.IMAGE_URL.path)

      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah    
      securityContext:
        capabilities:
          add: ["SETFCAP"]
      resources: {}
  workspaces:
  - mountPath: /files
    name: files