apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image-to-quay
spec:
  params:
    - name: quay-io-account
      description: The quay.io account that matches the credentials stored in the mounted secret
      type: string
      default: ""
    - name: quay-io-repository
      description: The quay.io repository in which to store the image.
      type: string
      default: ""
    - name: quay-io-image-tag-name
      description: The tag to use to identify the image.
      type: string
      default: "latest"
    - name: STORAGE_DRIVER
      description: The Buildah storage STORAGE_DRIVER
      type: string
  results:
    - name: IMAGE_DIGEST
      type: string
    - name: IMAGE_URL
      type: string
  steps:
    - name: buildah-tag-image
      command:
        - buildah
        - tag
        - '--storage-driver=$(params.STORAGE_DRIVER)'
        - '--root'
        - '/files/buildah-containers'
        - 'my-container-image:latest'
        # - 'quay.io/$(params.quay-io-account)/$(params.quay-io-repository):$(params.quay-io-image-tag-name)'
        - 'quay.apps.cluster-l6cp9.l6cp9.sandbox1607.opentlc.com/$(params.quay-io-account)/$(params.quay-io-repository):$(params.quay-io-image-tag-name)'
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
      securityContext:
        capabilities:
          add: ["SETFCAP"]
      resources: {}
    - name: list-images
      command:
        - buildah
        - images
        - '--storage-driver=$(params.STORAGE_DRIVER)'
        - '--root'
        - '/files/buildah-containers'
      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
      securityContext:
        capabilities:
          add: ["SETFCAP"]
      workingDir: /
      resources: {}
    - name: push-image-to-quay
      script: |
        buildah push --storage-driver=$(params.STORAGE_DRIVER) --authfile /etc/secret-volume/.dockerconfigjson \
        --root /files/buildah-containers --digestfile /tmp/image-digest \
        # quay.io/$(params.quay-io-account)/$(params.quay-io-repository):$(params.quay-io-image-tag-name)
        quay.apps.cluster-l6cp9.l6cp9.sandbox1607.opentlc.com/$(params.quay-io-account)/$(params.quay-io-repository):$(params.quay-io-image-tag-name)

        cat /tmp/image-digest | tee $(results.IMAGE_DIGEST.path)

        echo "quay.apps.cluster-l6cp9.l6cp9.sandbox1607.opentlc.com/$(params.quay-io-account)/$(params.quay-io-repository):$(params.quay-io-image-tag-name)" | tee $(results.IMAGE_URL.path)

      image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/buildah
      securityContext:
        capabilities:
          add: ["SETFCAP"]
      volumeMounts:
        - name: quay-auth-secret
          mountPath: /etc/secret-volume
          readOnly: true
  volumes:
    - name: quay-auth-secret
      secret:
        secretName: quay-auth-secret
  workspaces:
  - name: files
    mountPath: /files
