apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-source-commits
spec:
  description: This task verifies the latest commit and signature against a gpg public key
  results:
    - name: git-verify-result
  steps:
  - name: git-verify
    # image: alpine/git:latest
    image: image-registry.openshift-image-registry.svc:5000/secure-pipeline-ci/terminal:latest
    resources: {}
    script: >-
      #!/usr/bin/env bash

      failTask="true"

      gpg --import /workspace/secrets/public.key
      git config --global --add safe.directory /workspace/repository
      git verify-commit HEAD  > gitVerifyResult  2>&1
      gitVerifyResultVar=`cat gitVerifyResult`
      if [[ "$gitVerifyResultVar" == *"gpg: Good signature from"* ]]; then  
          failTask=false 
      else 
          echo "$gitVerifyResultVar"
      fi

      if [[ "$failTask" == "true" ]]; then  
        echo "Setting overall result to fail" 
        echo -n "fail" | tee $(results.git-verify-result.path) >> /dev/null 
      else
        echo "Setting overall result to pass" 
        echo -n "pass" | tee $(results.git-verify-result.path) >> /dev/null 
      fi

    workingDir: /workspace/repository
  workspaces:
  - name: repository
  - name: secrets
